### ISSUE TITLE
EchoPets support for spigot 1.9

### ISSUE THREAD

**Issue by mibby** [DSH105/EchoPet#605]
@DSH105 EchoPets does not currently support 1.9. :(

**Comment by Internetpilot** [comment]
Just chiming in also hoping for an update for 1.9!

**Comment by CaptainBern** [comment]
EchoPet is no longer being developed. Maybe when Sponge is more stable, we'll work on a Sponge version (though that's not a sure thing at all). But for now it's discontinued.

**Comment by DSH105** [comment]
project is *permanently* discontinued.

**Comment by Internetpilot** [comment]
Well that's disappointing.  Can't it be turned over to someone who is willing to continue it?  It's not really right to leave your users just hanging like this.

**Comment by CaptainBern** [comment]
@InternetPilot the problem is that it's quite hard to find someone willing to update this and not just wanting to make money by selling it. Also, about the "it's not really right to leave your users just hanging like this": EchoPet is libre software. If anyone whishes to update it, or add features, they can. But you can't really demand full-time support and a lifetime of updates on stuff you got for free.

**Comment by DSH105** [comment]
if you take a look at the development stream for the project, it's been slowly on its way out for a long time:
![fullsizerender](https://cloud.githubusercontent.com/assets/2748046/13544590/b5754ee6-e2cb-11e5-9c3c-cf9f5b62bb21.jpg)

Oct 2014 was the last to receive any notable bug patches and/or features outside of the incremental game version. I have not had any software tools installed on my computer since early 2015 and any maintenance on this repository was done either through my phone or on the web. I felt this decline was a softer exit and would warrant the creation of new pet projects as suitable replacements (of which I have seen a few).

If you do manage to find someone willing to put in the effort I did they are welcome to fork and continue it a their will, but this official branch of the project will not be seeing any further work from me. I would **strongly prefer** if they don't piggy-back off the EchoPet brand and instead use this repository as a guide for creating something similar and yet still unique. I'm sure that some will respect this but it's not for me to chase up.

Sorry for the disappointment, but I'd recommend finding yourself another pet project to support. For the skeptical, money is not an issue; as a teenage hobby this was never intended to provide any monetary output anyway.

**Comment by RarePika** [comment]
I would say "Please, just one more update", but that's not accurate, as more versions of minecraft will still come out for years 😢. I need to ask, where do you store data for the spigot version. I just want to toggle the version and that's it. Thanks.

**Comment by CaptainBern** [comment]
@RarePika If updating this plugin would be as simple as just changing "1.8" to "1.9", then the update would have been ready 2 weeks ago.

**Comment by RarePika** [comment]
@CaptainBern If that is true, I'm doomed. But, I want to let you know that all my other 1.8 plagins work in 1.9. I wanna try to remove the version restriction and try it. So I ask you again, where are the version files located.

**Comment by Internetpilot** [comment]
It wasn't really my intent to chastise the dev so much -- in reading my post again, I can see how it could be read that way.  No disrespect was meant...just disappointment.

If you do a search for Spigot, Minecraft, Bukkit, etc. pet plugins, almost every single result leads you right here.  There simply aren't any pet plugins out there that are anything like the ease of use (for the users) of EchoPet.  I'm currently trying MyPet, and users are already complaining about how complicated it is, how you have to manually tame a pet (like you would in vanilla Minecraft) first, and then you have to go through a kludgy process of "leashing" them that more often than not just results in you killing them, and all this is not even mentioning that you have to find the mob first, because you don't just got to conjure one up with a designated tool and gui menu.  Then you have to train it in order to ride it, you have to worry about whether or not you want users to be able to fight with their pets (which brings an air of cock/dog fighting to a game mostly targeted to children), etc.  It's supposedly written this way because it focuses on $ for the server owner.  

Honestly, since when are we all supposed to get rich off of a Minecraft server?  I don't charge a dime and I'm self-hosted on my own equipment. To clarify, the $ comments aren't directed at the original dev -- it's directed at the comment of not being able to find a dev who will continue to keep the project free. It's also directed at anyone and everyone trying to make $ off of children.     

I don't want to turn this into a rant thread (too late, I know...), but I'm just trying to better explain my disappointment, why I was such a fan of EchoPet, and why I'd really like to have seen it continue, and if not with the original dev then with a replacement one.

**Comment by CaptainBern** [comment]
@RarePika No offense but if you don't understand why changing every occurrence of "1.8" to "1.9" won't make it work, then you simply don't understand EchoPet well enough. It's not a project that everyone who can code a basic "hello world" application can update. It takes skill and a lot of effort to do so. Also, the files you talk about have to be recreated for every single update. Hence why it takes so much effort to update and maintain this project.

@Internetpilot Fair enough, We're well aware that EchoPet is probably one of the more populair pet plugins out there but the workload is simply too much, and definitely for 1 developer alone. What I said still stands tho; if anyone wants to update the plugin: feel free to do so. Thing is that a lot of people attempt to do that and then drop it because it's just too much work.

**Comment by RarePika** [comment]
@DSH105 @CaptainBern I still can't believe you guys just gave up on the best pet plugin of all time. Shame.

**Comment by FatherWh0** [comment]
@CaptainBern "the problem is that it's quite hard to find someone willing to update this and not just wanting to make money by selling it."
I have found someone who is willing to update this plugin for free. He has no interest in making profit from it. Unfortunately his efforts have been hindered by the fact that the maven repo is incomplete. Attempts to contact DSH105 about this have failed.

**Comment by CaptainBern** [comment]
@FatherWh0 DSH isn't availble anymore so in case you have any questions or whatever, ask them in #dsh105 on espernet (If I'm online I'll always be willing to answer). 

As for the maven repo issue, yeah it's because some projects got moved to another repo etc. I guess the issue is with Minecraft-Reflection which currently isn't available on any repo atm. (if anyone has decided to host it somewhere, let me know so I can update the readme so people know where to find it!).

To fix that: clone Minecraft-Refection and add it to your local maven repository. (Do that with any project missing from the remote maven repo(s))

**Comment by RarePika** [comment]
If this update is released, I will be the happiest miner alive. (SERVER: RarePika was blown up by a Creeper while chatting)

**Comment by phillmac** [comment]
Ok I've cloned all the projects for the missing maven repos, but the issue I'm running into now is the UUIDFetcher in the Comodus library  has an issue in the getUUIDOF(string name)  method,
The line "return getCache().get(name)" has an error:

com/dsh105/commodus/UUIDFetcher.java:[115,25] error: method get in interface Cache<K,V> cannot be applied to given types;

If I could fix that I'd be well on the way to an update.

any help much appreciated, ~Phill

**Comment by CaptainBern** [comment]
@phillmac try changing the `getCache().get(name);` to `getCache().getIfPresent(name);`.

**Comment by ghost** [comment]
Everyone on my server has been waiting for this :D

**Comment by harrydevane** [comment]
@CaptainBern Not sure if you still require it, but I put Reflection up on my repo for you(https://repo.harry5573.uk/content/repositories/releases/com/captainbern/Minecraft-Reflection/)

**Comment by CaptainBern** [comment]
@Harry5573 Neat. Thank you :).

**Comment by brainsynder** [comment]
Hello just enlighting some users who are down that echo pets is not being "maintained" i have made a pets plugin called SimplePets it is 1.8 and 1.9 compatable with alot of features and more on the way!

**Comment by Internetpilot** [comment]
EchoPet has been branched to SonarPet and as of a recent release is now working in 1.9. I'm running out on my 1.9 Spigot server right now.

**Comment by FatherWh0** [comment]
You link posted on echopet project page comes up as no perm to view. I assumed at first it wasn't accepted yet but a few days have passed.

**Comment by DSH105** [comment]
sorry, this isn't an advertising space.
